### ISSUE TITLE
(This is not an issue) but Just wanted to ask

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#10]
So trying to create a test firewall step / playbook to checkout backend connections

Like to SSH into the OVA Appliance and run the tools command to test all network connections to the back end junctions etc.

Anyone been able to use an Ansible module to accomplish this?

Thanks

**Comment by ram-ibm** [comment]
Please have a look at ISAM v9.0.3 (you can download from FixCentral). This release has a REST API for the express purpose of testing network connections using REST API.
