### ISSUE TITLE
Issue with report_junctions

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#15]
- name: Create a report on all Junctions
  hosts: all
  no_log: false
  connection: local
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_config

    - role: get_reverseproxies

    - role: get_junctions

    - role: get_junction_details

    - role: gen_report
      gen_report_template: "report_junctions.template"
      gen_report_dir: "/tmp"

Ouptput shows this:

TASK [gen_report : Generate Report using template report_junctions.template] ***
 [WARNING]: Unable to find 'base_commands.yml' in expected paths.
fatal: [ciaisawd0005.sys.cigna.com]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: base_commands.yml"}

**Comment by ram-ibm** [comment]
Please provide the version of Ansible you are using - I believe we are leveraging features of v2.3 of Ansible.

**Comment by Scoi4101** [comment]
DOH!

ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

**Comment by Scoi4101** [comment]
Same issue with
ansible 2.3.1.0

**Comment by ram-ibm** [comment]
I am not finding any problems related to the error you provided. Could you run with -vvv parameter and provide the output please?

This is pure speculation - but for some reason it looks like it is not running the gen_report role with connection as local...

**Comment by Scoi4101** [comment]
[output.txt](https://github.com/IBM-Security/isam-ansible-roles/files/1065227/output.txt)

**Comment by ram-ibm** [comment]
There is no lookup plugin being called anywhere that I looked. So it is truly unclear why you are having the problem. We could add a line to the gen_report plugin to ensure your report is being run locally.

```
# - name: Generate Report using template {{gen_report_template}}
  template:
    src : "{{role_path}}/files/{{gen_report_template}}"
    dest: "{{gen_report_dir}}/{{gen_report_template.partition('.')[0]}}_{{ansible_date_time.date}}-{{ansible_date_time.hour}}-{{ansible_date_time.minute}}-{{ansible_date_time.second}}.html"
  run_once: True
  changed_when: False
  delegate_to: localhost
  when: gen_report_template is defined and gen_report_dir is defined
```

Could you edit your role in /CIGNA/ansible-controller/isam-ansible-roles/gen_report/tasks/main.yml and try it out please?

There is something in your setup that is messing things up. Just not sure what yet...

**Comment by Scoi4101** [comment]
Same Issue

**Comment by ram-ibm** [comment]
Please do the following:
1. touch a file like so:
`touch /tmp/testing`

2. Create a playbook test.yml with following contents:
```
- name: Copy using template
  hosts: all
  no_log: True
  connection: local
  tasks:
  - name: Copy a file
    template:
      src : "/tmp/testing"
      dest: "/tmp/testing.out"
    run_once: True
    changed_when: False
    delegate_to: localhost
```

3. Execute playbook - provide any valid inventory (will be ignored):
`ansible-playbook -i <inventory> test.yml

The error seems to be how the template module is being invoked. So I am stripping everything else away from the playbook. 

Reference for template module:
http://docs.ansible.com/ansible/template_module.html

**Comment by Scoi4101** [comment]
Works

cilsdbxd10541 $ ansible-playbook test.yml

PLAY [Copy using template] ********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************
ok: [localhost]

TASK [Copy a file] ****************************************************************************************************************************************************************
ok: [localhost -> localhost]

PLAY RECAP ************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

**Comment by ram-ibm** [comment]
Please try running the junctions report - but limit it to a server with the fewest junctions.

Also you may want to check if your OS level ulimits are high enough?

The report works by collecting all the data into a huge data structure and then dumping it to a file. So I want to eliminate if there is a problem with the OS limiting Ansible from completing.

**Comment by Scoi4101** [comment]
This VM has one RP with One junction to limit that as well.

**Comment by ram-ibm** [comment]
So if the issue is not with creating a huge data structure - then it has to do with jinja2 templating.

In the previous test.yml file, trying adding this to the /tmp/testing file created and re-running test.yml:
```
{% for h in play_hosts %}
  {{ h }}
{% endfor %}
```

Best to give it an inventory file though when you run it. It should list all the hostnames in your inventry.

**Comment by Scoi4101** [comment]
Not seeing the output

cilsdbxd10541 $ ansible-playbook -i @inventories/0-DFLT test.yml

PLAY [Copy using template] ********************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************
ok: [ciaisaps0001.sys.cigna.com]
ok: [isam902t4.silver.com]
ok: [isam902t6.silver.com]
ok: [ciaisawd0005.sys.cigna.com]
ok: [isam902t7.silver.com]
ok: [ciaisawd0008.sys.cigna.com]

TASK [Copy a file] ****************************************************************************************************************************************************************
ok: [ciaisawd0005.sys.cigna.com -> localhost]

PLAY RECAP ************************************************************************************************************************************************************************
ciaisaps0001.sys.cigna.com : ok=1    changed=0    unreachable=0    failed=0
ciaisawd0005.sys.cigna.com : ok=2    changed=0    unreachable=0    failed=0
ciaisawd0008.sys.cigna.com : ok=1    changed=0    unreachable=0    failed=0
isam902t4.silver.com       : ok=1    changed=0    unreachable=0    failed=0
isam902t6.silver.com       : ok=1    changed=0    unreachable=0    failed=0
isam902t7.silver.com       : ok=1    changed=0    unreachable=0    failed=0

**Comment by ram-ibm** [comment]
Check /tmp/testing.out - the output should be in there. There should be a list of the hosts (six as per the execution above)  in that file.

**Comment by Scoi4101** [comment]
Sorry yep misunderstood that

**Comment by ram-ibm** [comment]
This is a really perplexing error. But I am trying to circle around to try and narrow down the issue. Wonder if the "roles_path" variable is not getting defined.

```
 - name: Generate Report using template {{gen_report_template}}
  template:
    src : "/CIGNA/ansible-controller/isam-ansible-roles/gen_report/files/report_junctions.template"
    dest: "/tmp/report_junctions.html"
  run_once: True
  changed_when: False
  delegate_to: localhost
  when: gen_report_template is defined and gen_report_dir is defined
```

Could you confirm that the file in "src" field in the code below exists? If not, could you fix it and then try running it please?

**Comment by Scoi4101** [comment]
cilsdbxd10541 $ **cat /CIGNA/ansible-controller/isam-ansible-roles/gen_report/tasks/main.yml**
- name: Generate Report using template {{gen_report_template}}
  template:
    src : "/CIGNA/ansible-controller/isam-ansible-roles/gen_report/files/report_junctions.template"
    dest: "/tmp/report_junctions.html"
  run_once: True
  changed_when: False
  delegate_to: localhost
  when: gen_report_template is defined and gen_report_dir is defined
cilsdbxd10541 $ **ls -lrt /CIGNA/ansible-controller/isam-ansible-roles/gen_report/files/report_junctions.template**
-rwxrwxrwx 1 devops devops 1884 Jun  5 13:13 /CIGNA/ansible-controller/isam-ansible-roles/gen_report/files/report_junctions.template

**Comment by Scoi4101** [comment]
[massive_detail_junction_report.txt](https://github.com/IBM-Security/isam-ansible-roles/files/1068917/massive_detail_junction_report.txt)
[report.txt](https://github.com/IBM-Security/isam-ansible-roles/files/1068921/report.txt)

So adding to the weird but progress
its the hostvars execution for the hostname that fails for me.

More to come.

**Comment by ram-ibm** [comment]
The next steps I had in mind was similar to what you are doing.

1. Try running the playbook but use the /tmp/testing instead of /CIGNA/ansible-controller/isam-ansible-roles/gen_report/files/report_junctions.template

2. Based on how it was running I was thinking of trying various options within /tmp/testing

3. Using debug option to dump variables is another option. But I think hostvars[inventory_hostname] maybe the wrong way to reference it. Simply trying dumping out all of hostvars instead. The index might be a sequence number.

**Comment by Scoi4101** [comment]
FACEPALM ......

pdadmin_commands: "{{ lookup('file', 'base_commands.yml') }}" 
**that was in group_vars/all/vars.yaml**

Ram I owe you a drink next conference.

**Comment by ram-ibm** [comment]
I am glad you were able to resolve it!
