### ISSUE TITLE
logger broken

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-roles#166]
As I was troubleshooting another issue, I almost became crazy because I could no longer see any logger() statement displayed in console with "-vvv" passed to Ansible. (-;

Apparently, recent code change (https://github.com/IBM-Security/isam-ansible-roles/commit/6048a398d6148b4bfacbb36842410f81163aeea2#diff-fab442aaab4b16a2eb0a40fda197d58d) makes logging not working anymore (only in V2.7?). I believe this has to do with how the StringIO is imported.

I replaced in isam.py the following:

> from io import StringIO

With this (as before):

> from StringIO import StringIO

And everything got resolved.

What is the proper way to resolve this ?

**Comment by sygilber** [comment]
@djorgen-ibm would appreciate your input in this one. Thanks

**Comment by ram-ibm** [comment]
I am trying to find the issue here between python 2 and 3. Any chance you found any documentation that suggested using "from StringIO import StringIO" please?

**Comment by sygilber** [comment]
PR 166 submitted

**Comment by sygilber** [comment]
Resolved with merge https://github.com/IBM-Security/isam-ansible-roles/pull/168
