### ISSUE TITLE
delete_certdb_personal_cert DEBUG enable issue

### ISSUE THREAD

**Issue by rfransix** [IBM-Security/isam-ansible-roles#169]
Hi, uncommenting the debug lines causes a missing quote somewhere and the play fails immediately. Let me know if you see the fix. Thank you.
The goal is to use debug to output the kdb id on failure.

cat main.yml
main.yml
- name: Set Fact
  set_fact:
    kdb2_id: "{{  cert_db_id  }}"

- name: Get list of Personal Certificates in Keystore
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.personal_certificate.get_all
    isamapi:
      kdb_id: "{{  cert_db_id  }}"
  register: ret_obj

- name: Set variable for use by rest of playbook
  set_fact:
    certdbs_personallist_ret_obj: "{{ ret_obj }}"

#- name: Output
#  debug:
#    msg="{{ kdb2_id }} {{ item['id'] }} {{ item['notafter_epoch'] }}"
#  with_items:
#   - "{{certdbs_personallist_ret_obj['data']}}"
#  when: ({{ item['notafter_epoch'] }} < {{ ansible_date_time.epoch }})

- name: Delete Certificate
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.personal_certificate.delete
    isamapi:
      kdb_id: "{{  kdb2_id  }}"
      cert_id: "{{ item['id'] }}"
  when: ({{ item['notafter_epoch'] }} < {{ ansible_date_time.epoch }})
  with_items:
    - "{{certdbs_personallist_ret_obj['data']}}"
  notify:
    - Commit Changes

**Comment by rfransix** [comment]
Using yamllint, i change the debug statement to this:
- name: Output
  debug: "msg=\"{{ kdb2_id }} {{ item['id'] }} {{ item['notafter_epoch'] }}\""
  with_items:
    - "{{certdbs_personallist_ret_obj['data']}}"
  when: "({{ item['notafter_epoch'] }} < {{ ansible_date_time.epoch }})"

And the play returns...any ideas, why?
TASK [delete_certdb_personal_cert : Output] **********************************************************************************************************************************************
[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ({{ item['notafter_epoch'] }} < {{ ansible_date_time.epoch }})

**Comment by rfransix** [comment]
Trying this approach did not output the kdb id : 
- name: Output
  debug: "msg=\"{{ kdb2_id }} {{ item['id'] }} {{ item['notafter_epoch'] }}\""
  with_items:
    - "{{certdbs_personallist_ret_obj['data']}}"
##  when: "({{ item['notafter_epoch'] }} < {{ ansible_date_time.epoch }})"
  when: "( item['notafter_epoch'] < ansible_date_time.epoch )"

**Comment by rfransix** [comment]
Valid YAML! --- checked in www.yamllint.com too.

**Comment by rfransix** [comment]
This is working with the above change on success only. Any idea on how to get it to work on failure or FATAL ?

**Comment by ram-ibm** [comment]
`[WARNING]: conditional statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: ({{ item['notafter_epoch'] }} < {{ ansible_date_time.epoch }})`

The key is the above warning. You do not need curly braces in the when clause. Something like this should work better (not tested):
`when: item['notafter_epoch'] < ansible_date_time.epoch`

I would also recommend dumping the entire variable in a debug statement first before iterating through lists.
```
- name: Output
  debug: "{{certdbs_personallist_ret_obj['data']}}"
```

Start like above and then add what you need.

**Comment by rfransix** [comment]
Hi, that’s right. I removed the braces and got rid of that error.

After that, deleting both signers and personals processed without errors.
