### ISSUE TITLE
delete lmi sysaccount user and group

### ISSUE THREAD

**Issue by rfransix** [IBM-Security/isam-ansible-roles#177]
Hi, after building a delete_sysaccount_user (from add_sysaccount_user) role, and setting the vars to existing user and group that need to be deleted, we get...is deleting lmi users/groups still not possible...notice how i changed the action from *create* to "delete*.

TASK [delete_sysaccount_user : Delete LMI system account user] ******************************************************************************************************************************
fatal: [host.net.com]: FAILED! => {"changed": false, "log": "", "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=False, password=None, id=\"superuser\", groups=\"superuser\"", "name": "ibmsecurity.isam.base.sysaccount.users.delete"}

**Comment by ram-ibm** [comment]
Here is what the delete function is expecting:
`delete(isamAppliance, id, check_mode=False, force=False)`

Based on the error - you are passing:
`isamAppliance=isam_server, force=False, password=None, id="superuser", groups="superuser"`

You should not pass password, or groups. create() takes them but not delete.

**Comment by rfransix** [comment]
Thank you. removing groups from the main.yml solved the issue..
