### ISSUE TITLE
Consider adding a role to modify attribute source

### ISSUE THREAD

**Issue by kalemontes** [IBM-Security/isam-ansible-roles#179]
When using the role `isam-ansible-roles/add_attribute_source` it does not change the value of `attribute_source_value` if the attribute source already exists.
Removing the attribute source and adding it again is tedious because you have to detach it from the definitions first.
It'll be handy if I could easily change the value of `attribute_source_value` for a given attribute source.

**Comment by ram-ibm** [comment]
Please create a new set_attribute_source that uses the set() function. That will add if does not exist and modify if it already exists and a change is needed.
