### ISSUE TITLE
First steps fails with ERROR! conflicting action statements: include, dynamic

### ISSUE THREAD

**Issue by tombosmansibm** [IBM-Security/isam-ansible-roles#182]
This happens on Ansible 2.9+

The solution is to remove dynamic , and add a name

**Comment by ram-ibm** [comment]
Yup need to fix this.

**Comment by tombosmansibm** [comment]
I have the fix, I just need to get it in this branch. Tomorrow :-)

**Comment by tombosmansibm** [comment]
https://github.com/IBM-Security/isam-ansible-roles/pull/185
