### ISSUE TITLE
Update RP Conf Role

### ISSUE THREAD

**Issue by wdwill2wdwill2** [IBM-Security/isam-ansible-roles#19]
The current role updates a current entry.  However there are times when would like to "add" an entry to an existing stanza. (ie. logcfg=blah,blah,blah)

I tried creating a new role that uses the action ibmsecurity.isam.web.reverse_proxy.configuration.entry.add.   This is the message i get.

 "msg": "Error> action does not have the right set of arguments or there is a code bug!

**Comment by ram-ibm** [comment]
There are three roles:
```
update_reverseproxy_conf
set_reverseproxy_conf
add_reverseproxy_conf
```

The last one is the one you want for your current use case. Use update to update an existing single value, add to append to existing or non-existing entry and finally set to ensure that you get the exact set of multi-values you want assigned to an entry. It will ensure there is no more or less when you use set.

**Comment by wdwill2wdwill2** [comment]
Thanks Ram.   Sorry for missing those other roles
