### ISSUE TITLE
Feature(s) that would be nice to have

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#2]
I know the APIs aren't hard for these but these playbooks make it so easy.

1. Deploy / Rollback Pending Changes
2. Start / Stop / Restart Reverse Proxy Instance
3. Delete a Reverse Proxy Instance

**Comment by ram-ibm** [comment]
You may want to create your own playbooks for these. The commit/rollback I can post once I get sometime to fix some of the roles.

**Comment by ram-ibm** [comment]
This seems to be a common need - will post ones I have developed once I get a chance to test them a little better.

**Comment by jldement** [comment]
Scio4104 - you closed the pdadmin issue; not sure if you solved it or gave up.  In case you did not solve it, is this closer to what you were looking for:
pdadmin.yml
---
# Run PDAdmin commands - against all but restricted appliances

- name: Run PDAdmin command(s) against an appliance
  # hosts: all:!restricted
  hosts: standalone
  connection: local
  vars:
    instance: "{{ lookup('pipe', 'cat /home/jdement/isam-ansible-playbook-sample/instance | cat -') }}"
    pdadmin_commands: "{{ lookup('pipe', 'sed -e \"s/instance/{{instance}}/\" /home/jdement/isam-ansible-playbook-sample/pdadmin_file') }}"
    sec_master_id: "sec_master"
    sec_master_pwd: "passw0rd"
    isam_domain: "Default"
    username:  "admin"
    password:  "passw0rd"
    lmi_port:  "443"
    log_level: "DEBUG"

  roles:
    - role: execute_pdadmin
      execute_pdadmin_commands: "{{ pdadmin_commands }}"
      execute_pdadmin_domain:   "{{ isam_domain }}"
      execute_pdadmin_isamuser: "{{ sec_master_id }}"
      execute_pdadmin_isampwd:  "{{ sec_master_pwd }}"

  tasks:
     - debug: msg="the value of pdadmin_file is {{pdadmin_commands}}"
     - debug: msg="the value of instance is {{instance}}"


file instance:
default-webseald-isam9021dz

file pdadmin_file:
server list
server task instance list
object show /WebSEAL/instance

**Comment by jldement** [comment]
display messed up a little.    Contents of pdadmin.yml immediately follow that line, not sure why all the caps and bold on the line "Run PDAdmin commands - against all but restricted appliances".

**Comment by Scoi4101** [comment]
Ah very nice solution to the problem. Thank you.
