### ISSUE TITLE
Report Junction Template and ISAM Version

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#20]
Should the Report Junction Template work on ISAM version 9.0.1?

All of the 9.0.2 instances work fine but on 9.0.1 it seems to only pull the first server junction point
Did the format of the servers attribute change between versions ?

Thanks

**Comment by ram-ibm** [comment]
I think I saw an issue with how the server information is separated. 
```
def get(isamAppliance, reverseproxy_id, junctionname, check_mode=False, force=False):
    """
    Retrieving the parameters for a single standard or virtual junction

    :param isamAppliance:
    :param reverseproxy_id:
    :param junctionname:
    :param check_mode:
    :param force:
    :return:
    """
    ret_obj = isamAppliance.invoke_get("Retrieving the parameters for a single standard or virtual junction",
                                       "{0}/{1}/junctions?junctions_id={2}".format(uri, reverseproxy_id,
                                                                                   junctionname),
                                       requires_modules=requires_modules,
                                       requires_version=requires_version)
    # servers are provided as a single string, here we parse it out into a list + dict
    servers = []
    srvs = ret_obj['data']['servers'].split('#')
    logger.debug("Servers in raw string: {0}".format(ret_obj['data']['servers']))
    logger.debug("Number of servers in junction: {0}".format(len(srvs)))
    for srv in srvs:
        logger.debug("Parsing Server: {0}".format(srv))
        server = {}
        for s in srv.split(';'):
            if s != '':
                kv = s.split('!')
                server[kv[0]] = kv[1]
        servers.append(server)

    ret_obj['data']['servers'] = servers

    return ret_obj
```

In the above code I think we may need to fix `kv = s.split('!')` to split on '&' for v9.0.1. It will be helpful if you can provide a JSON output for a junction from v9.0.1.

**Comment by Scoi4101** [comment]
[web_901_junction.txt](https://github.com/IBM-Security/isam-ansible-roles/files/1163058/web_901_junction.txt)

Sorry for the delay please find the JSON attached

**Comment by ram-ibm** [comment]
Just as I suspected - I made the fix to character used to separate the servers without realizing that it was a difference between versions. I thought I had coded it wrong and that is why it was not working for v9.0.2 onwards.

**Comment by ram-ibm** [comment]
I pushed a code change - please reopen if the code does not work. I do not have a v9.0.1 ti test right now.
