### ISSUE TITLE
import license support file

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-roles#35]
We have developed a role to import the support license file. We intent to share it but I was wondering if it should be named “import_license”, “apply_license”, or “install_license”.  The actual python code and rest api documentation both refer to the act of “installing” a license whereas the appliance web help refers of “importing”. I don’t think that one can add numerous license file (although I never tried) so I was ruling out the “add” semantics. Open to comments.  Will later track the pull request to this issue.

**Comment by ram-ibm** [comment]
Lets go with install since the python function has that name. I agree that we have multiple valid options for this.
