### ISSUE TITLE
Change Access Control Runtime Listening parameters

### ISSUE THREAD

**Issue by wdwill2wdwill2** [IBM-Security/isam-ansible-roles#37]
Is there a way to change the interface on the runtime listening interfaces under Secure Access Control
(ie i want to change it from local interface to 1.2)
Thanks
Bill

**Comment by ram-ibm** [comment]
There is python function to do this. See ibmsecurity.isam.base.runtime.listening_interfaces.set(). There is also a role called add_runtime_listening_interface.
