### ISSUE TITLE
WGA entry set could not remove entry value with special characters

### ISSUE THREAD

**Issue by mlu-ibm** [IBM-Security/isam-ansible-roles#4]
While calling set_reverseproxy_conf role to set 'request-log-format', it failed when tried to remove the default value which has '%' character:

```
'HTTP Return code: 500', u'<H1>SRVE0232E: Internal Server Error. <br> Exception Message: [URLDecoder: Illegal hex characters in escape (%) pattern - For input string: \"h%\"]</H1><BR><H3>URLDecoder: Illegal hex characters in escape (%) pattern - For input string: \"h%\"</H3><BR><I>IBM WebSphere Application Server</I>' 
```

I suspect that the input was not properly URLEncoded when calling the API to delete the entry.

**Comment by ram-ibm** [comment]
Python code has been updated to encode URI properly.
