### ISSUE TITLE
Addition of new stanza

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-roles#43]
Sometime it is necessary to add some stanza to ISAM RP configuration files (for junction related settings or cred attributes setup) as it is described in the ISAM federation cookbook.

So we have developed a specialized role for dealing with the addition of non-existing stanza to ISAM RP configuration files (called add_reverseproxy_conf_stanza using stanza.py). But I wonder if instead we should not extend the implementation of the existing add_reverseproxy_conf  role to have it detect automatically if entries/values pairs are to be added/updated for stanza that are not yet defined, and proceed with adding those automatically. Similarly, the update_reverseproxy_conf could be updated similarly.

Extending the roles such as add_reverseproxy_conf (as opposed to provide a new one) would help limit the proliferation of small utilities roles and help playbook developer get the job done more easily. 
Should update_reverseproxy_conf  deserve the same treatment?

What are your thoughts?

**Comment by ram-ibm** [comment]
add_reverseproxy_conf role adds a stanza if it does not exist. Try it.

**Comment by sygilber** [comment]
You are totally right. I was able to use the role un-modified and do the following with a slightly different formatting twist:
    - role: add_reverseproxy_conf
      add_reverseproxy_conf_reverseproxy_id: "default"
      add_reverseproxy_conf_entries:
        - stanza_id: "missing_stanza"
          entries:
            - - "someid"
              - "somevalue"
            - - "someotherid"
              - "someothervalue"
            - - "someother3id"
              - "someother3value"

And I obtained in the RP conf the following:

[missing_stanza]
someid = somevalue
someotherid = someothervalue
someother3id = someother3value

I could also use another YAML formatting style (learning all formatting variations as I type):

   - role: add_reverseproxy_conf
     tags: ["web", "reverseproxy", "stanza"]
     add_reverseproxy_conf_reverseproxy_id: "default"
     add_reverseproxy_conf_entries:
       - stanza_id: "missing_stanza"
         entries:
           - [ "someid", "somevalue" ]
           - [ "someotherid", "someothervalue" ]
           - [ "someother3id", "someother3value" ]
           - [ "someother4id", "someother4value" ]

and I obtained the following in the RP conf file:

[missing_stanza]
someid = somevalue
someotherid = someothervalue
someother3id = someother3value
someother4id = someother4value

Thanks, case closed.
