### ISSUE TITLE
set_junction role calls the add junction function

### ISSUE THREAD

**Issue by LouBea** [IBM-Security/isam-ansible-roles#46]
In the set_junction role the action being called in main.yml is:

**action: ibmsecurity.isam.web.reverse_proxy.junctions.add**

Is there a reason why it doesn't call the **ibmsecurity.isam.web.reverse_proxy.junctions.set** function?

And if there is what is the correct role to use to call the set junction?

As a sub-question, why would there be an add_junction role? From what I understand the set function does the idempotence check & calls add if needed. Why would someone want to use add directly instead of using set?

Thanks !!

**Comment by ram-ibm** [comment]
It should be calling set() - I am wondering if I need to submit a merge. I see it in my local repository.

**Comment by ram-ibm** [comment]
Actually I dont - this needs to be fixed.

**Comment by sygilber** [comment]
Resolved with https://github.com/IBM-Security/isam-ansible-roles/pull/49
