### ISSUE TITLE
add_junction or set_junction refer to server_uid

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-roles#48]
These 2 roles use "server_uid" instead of "server_uuid" and this caused the roles to fail with message "action does not have the right set of arguments or there is a code bug!".

Will submit a fix/pull request eventually for this. I recall having seen earlier this year changes in ibmsecurity regarding server_uuid updates in the code.

Any thoughs on this issue as to why the old wrong paramater may still be refered in roles ? A simple over-loooked issue or a backward appliance (rest api) compatibility issue ?

Thanks

**Comment by ram-ibm** [comment]
Over-looked issue - I fixed the python code but did not get to the roles. Please submit a pull request. Thanks.

**Comment by sygilber** [comment]
Resolved with https://github.com/IBM-Security/isam-ansible-roles/pull/49
