### ISSUE TITLE
set_admin_cfg working example available ?

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-roles#50]
Hi

Anyone having a working playbook using the role set_admin_cfg ?

I keep getting the error msg "action does not have the right set of arguments or there is a code bug" when running a very simple role:

    - role : set_admin_cfg
      set_admin_cfg_key : "enableSSLv3"
      set_admin_cfg_value : "false"

fatal: [stha9n0fw.iad.ca.inet]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "action": "ibmsecurity.isam.base.admin.set",
            "appliance": "**********",
            "force": false,
            "isamapi": {
                "key": "enableSSLv3",
                "value": "false"
            },
            "lmi_port": 443,
            "log": "DEBUG",
            "password": "*********",
            "username": "admin@local"
        }
    },
    "log": "[2017-12-11 16:37:39,746] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.user.applianceuser] [__init__():9] Creating a user\n[2017-12-11 16:37:39,746] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.user.user] [__init__():8] Creating a user\n[2017-12-11 16:37:39,746] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.isamappliance] [__init__():13] Creating an ISAMAppliance\n[2017-12-11 16:37:39,746] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [__init__():15] Creating an IBMAppliance\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving firmware ***\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2017-12-11 16:37:39,747] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://stha9n0fw.iad.ca.inet:443/firmware_settings\n[2017-12-11 16:37:39,749] [PID:2535 TID:140474922600256] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): stha9n0fw.iad.ca.inet\n[2017-12-11 16:37:40,085] [PID:2535 TID:140474922600256] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://stha9n0fw.iad.ca.inet:443 \"GET /firmware_settings HTTP/1.1\" 200 483\n[2017-12-11 16:37:40,088] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2017-12-11 16:37:40,088] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: [{\"partition\":\"1 (Active)\",\"last_boot\":\"1512828512\",\"name\":\"isam_9.0.3.1_20171017-2336\",\"active\":true,\"comment\":\"\",\"id\":1,\"firmware_version\":\"IBM Security Access Manager 9.0.3.1\",\"install_date\":\"1512396478\",\"backup_date\":null,\"install_type\":\"ISO\"}, {\"partition\":\"2\",\"last_boot\":\"Never\",\"name\":\"isam_9.0.3.1_20171017-2336\",\"active\":false,\"comment\":\"\",\"id\":2,\"firmware_version\":\"IBM Security Access Manager 9.0.3.1\",\"install_date\":\"1512396497\",\"backup_date\":null,\"install_type\":\"ISO\"}]\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Get Setup Complete Settings ***\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2017-12-11 16:37:40,089] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://stha9n0fw.iad.ca.inet:443/setup_complete\n[2017-12-11 16:37:40,090] [PID:2535 TID:140474922600256] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): stha9n0fw.iad.ca.inet\n[2017-12-11 16:37:40,323] [PID:2535 TID:140474922600256] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://stha9n0fw.iad.ca.inet:443 \"GET /setup_complete HTTP/1.1\" 200 21\n[2017-12-11 16:37:40,326] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2017-12-11 16:37:40,326] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: { \"configured\": true}\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving activations ***\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2017-12-11 16:37:40,327] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://stha9n0fw.iad.ca.inet:443/isam/capabilities/v1\n[2017-12-11 16:37:40,328] [PID:2535 TID:140474922600256] [DEBUG] [urllib3.connectionpool] [_new_conn():824] Starting new HTTPS connection (1): stha9n0fw.iad.ca.inet\n[2017-12-11 16:37:40,577] [PID:2535 TID:140474922600256] [DEBUG] [urllib3.connectionpool] [_make_request():396] https://stha9n0fw.iad.ca.inet:443 \"GET /isam/capabilities/v1 HTTP/1.1\" 200 None\n[2017-12-11 16:37:40,580] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2017-12-11 16:37:40,580] [PID:2535 TID:140474922600256] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: [{\"name\":\"ISAM Base Appliance\",\"description\":\"IBM Security Access Manager Base Appliance\",\"id\":\"wga\",\"enabled\":\"True\"}, {\"name\":\"ISAM Advanced Access Control\",\"description\":\"IBM Security Access Manager Advanced Access Control\",\"id\":\"mga\",\"enabled\":\"True\"}, {\"name\":\"ISAM Federation\",\"description\":\"IBM Security Access Manager Federation\",\"id\":\"federation\",\"enabled\":\"True\"}]\n",
    "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=False, key=\"enableSSLv3\", value=\"false\"",
    "name": "ibmsecurity.isam.base.admin.set"
}

**Comment by sygilber** [comment]
Our issue was resolved with this commit: 

https://github.com/IBM-Security/ibmsecurity/commit/6dbb57771cf7b41ceb8c6594f3059a5628c4d4f5

**Comment by wdwill2wdwill2** [comment]
Does this still work for you?  I'm at the latest commit and I receive the same error that you received.

Thanks
Bill

**Comment by sygilber** [comment]
Hi Bill

We are still using this role without any issue.

    - role: set_admin_cfg
      tags: ["system", "admin", "cfg"]

and with the following set in our ansible inventory:

set_admin_cfg_enableSSLv3: "False"
set_admin_cfg_enabledTLS: ["TLSv1.2"]

Could you please provide more traces/logs ?

**Comment by wdwill2wdwill2** [comment]
Here is my debug.  I've tried setting the variables in the playbook and in the default yml of the role.

fatal: [ciaisawd0018.sys.cigna.com]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "ibmsecurity.isam.base.admin.set",
            "adminProxyApplianceShortName": false,
            "adminProxyHostname": null,
            "adminProxyPort": 443,
            "adminProxyProtocol": "https",
            "appliance": "ciaisawd0018.sys.cigna.com",
            "force": false,
            "isamapi": {
                "key": "sessionTimeout",
                "value": 720
            },
            "lmi_port": 443,
            "log": "DEBUG",
            "omitAdminProxy": false,
            "password": "xxxxxx",
            "username": "admin@local"
        }
    },
    "log": "[2018-06-05 17:33:10,372] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.user.applianceuser] [__init__():9] Creating a user\n[2018-06-05 17:33:10,372] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.user.user] [__init__():8] Creating a user\n[2018-06-05 17:33:10,372] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.isamappliance] [__init__():13] Creating an ISAMAppliance\n[2018-06-05 17:33:10,372] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [__init__():46] Creating an IBMAppliance\n[2018-06-05 17:33:10,372] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():575] Request: GET /core/sys/versions desc=Retrieving version\n[2018-06-05 17:33:10,372] [PID:4673 TID:139900339087168] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving version ***\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-06-05 17:33:10,373] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://ciaisawd0018.sys.cigna.com:443/core/sys/versions\n[2018-06-05 17:33:10,494] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2018-06-05 17:33:10,494] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: {\"firmware_label\":\"isam_9.0.4.0_20171201-2325\",\"firmware_build\":\"20171201-2325\",\"firmware_version\":\"9.0.4.0\",\"product_description\":\"IBM Security Access Manager\",\"deployment_model\":\"Appliance\",\"product_name\":\"isam\"}\n[2018-06-05 17:33:10,494] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():579] Response: 0\n[2018-06-05 17:33:10,494] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():575] Request: GET /setup_complete desc=Get Setup Complete Settings\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Get Setup Complete Settings ***\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-06-05 17:33:10,495] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://ciaisawd0018.sys.cigna.com:443/setup_complete\n[2018-06-05 17:33:10,584] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2018-06-05 17:33:10,584] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: { \"configured\": true}\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():579] Response: 0\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():575] Request: GET /isam/capabilities/v1 desc=Retrieving activations\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():30] *** Retrieving activations ***\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():92] Checking for minimum version: None.\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():108] Checking for one of required modules: None.\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():125] Warnings: []\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():301] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():306] Input Data: {}\n[2018-06-05 17:33:10,585] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():35] Suppressing SSL Warnings.\n[2018-06-05 17:33:10,586] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():24] Issuing request to: https://ciaisawd0018.sys.cigna.com:443/isam/capabilities/v1\n[2018-06-05 17:33:10,694] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Status Code: 200\n[2018-06-05 17:33:10,694] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():65] Text: [{\"name\":\"ISAM Base Appliance\",\"description\":\"IBM Security Access Manager Base Appliance\",\"id\":\"wga\",\"enabled\":\"True\"}, {\"name\":\"ISAM Advanced Access Control\",\"description\":\"IBM Security Access Manager Advanced Access Control\",\"id\":\"mga\",\"enabled\":\"True\"}, {\"name\":\"ISAM Federation\",\"description\":\"IBM Security Access Manager Federation\",\"id\":\"federation\",\"enabled\":\"True\"}]\n[2018-06-05 17:33:10,694] [PID:4673 TID:139900339087168] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():579] Response: 0\n",
    "msg": "Error> action does not have the right set of arguments or there is a code bug! Options: isamAppliance=isam_server, force=False, value=720, key=\"sessionTimeout\"",
    "name": "ibmsecurity.isam.base.admin.set"
}

**Comment by ram-ibm** [comment]
Here is what the set() function looks like in the latest package:
'''
def set(isamAppliance, oldPassword=None, newPassword=None, minHeapSize=None, maxHeapSize=None, sessionTimeout=30,
        httpPort=None, httpsPort=None, minThreads=None, maxThreads=None, maxPoolSize=None, lmiDebuggingEnabled=None,
        consoleLogLevel=None, acceptClientCerts=None, validateClientCertIdentity=None, excludeCsrfChecking=None,
        enableSSLv3=None, maxFiles=None, maxFileSize=None, enabledTLS=None, sshdPort=None, check_mode=False,
        force=False):
'''

There is no key/value option in there as you are passing. I had revamped this code to match the other modules and it is possible that you have a version of the role that still refers to the old code.

**Comment by wdwill2wdwill2** [comment]
Ram…

I looked at the admin.py code and the set function is as you describe below.

def set(isamAppliance, oldPassword=None, newPassword=None, minHeapSize=None, maxHeapSize=None, sessionTimeout=30,
        httpPort=None, httpsPort=None, minThreads=None, maxThreads=None, maxPoolSize=None, lmiDebuggingEnabled=None,
        consoleLogLevel=None, acceptClientCerts=None, validateClientCertIdentity=None, excludeCsrfChecking=None,
        enableSSLv3=None, maxFiles=None, maxFileSize=None, enabledTLS=None, sshdPort=None, check_mode=False,
        force=False):

I looked at the set_admin_cfg role on Git and it is exactly the same that I have on my ansible controller.

- name: Set Administrator Configuration -  {{set_admin_cfg_key}}/{{set_admin_cfg_value}}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.admin.set
    isamapi:
      key   : "{{ set_admin_cfg_key }}"
      value : "{{ set_admin_cfg_value }}"
  when: set_admin_cfg_key is defined and set_admin_cfg_value is defined
notify: Commit Changes

Is the role on Git correct?

Thanks
Bill

**Comment by ram-ibm** [comment]
Bill - unfortunately the role is incorrect. The python code change was made sometime ago and we missed updating the role. I have working code - will get it into git.

**Comment by wdwill2wdwill2** [comment]
Thanks Ram.

**Comment by rfransix** [comment]
Hi, is sessionInactivityTimeout=60 included, not working for me?
