### ISSUE TITLE
Any "add_junction" working example? Keep getting error "action does not have the right set of arguments or there is a code bug"

### ISSUE THREAD

**Issue by alwayslearning321** [IBM-Security/isam-ansible-roles#51]
Hi need some help. Built ISAM 9 VM following "ISAM9 Federation Cookbook", and was able to use ansible on docker to do lots of things following "isam-ansible-playbook-sample" such as  run pdadmin commands, create snapshot, activate module, create reverse proxy,...etc.

However, "add_junction" always fail with error "action does not have the right set of arguments or there is a code bug" as shown below. Also tried just use "TestInstance" as "add_junction_reverseproxy_id", but still gets same error.
![addjunctionerror](https://user-images.githubusercontent.com/34525983/34086227-70ea9530-e3ee-11e7-8453-426e414a29aa.png)

If I commented out the "add_junction_reverseproxy_id" line then it just said "skipping" and nothing happened.
![addjunctionskipped](https://user-images.githubusercontent.com/34525983/34086429-cb7ca64a-e3ef-11e7-8c8c-aeabf2537d10.png)

Any idea what have I done wrong? Or is there any working example "add_junction" available?  Thanks.

**Comment by sygilber** [comment]
Hi. Did you refresh to the latest isam-ansible-roles lately ? Less than 2 weeks ago there as been fixes regarding the add/set junction roles, more particularly  rename of server_uid for server_uuid which before that caused such errors that you are observing now.

**Comment by alwayslearning321** [comment]
hi sygilber, you are right, after refresh it worked. thanks for your help. will close this issue.
