### ISSUE TITLE
set_cluster_config: AAC Runtime not restarted

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/isam-ansible-roles#58]
When HVDB changes occur, they are not effective automatically since the role is not notifying "Restart AAC Runtime" handler.

On the other hand, if the role would notify "Restart AAC Runtime", it would always initiate a restart of the AAC Runtime even when other cluster changes occured unrelated to the DB occured.

So I don't know what is best approach.

**Comment by ram-ibm** [comment]
The python code that will restart the AAC Runtime - will only do a restart if the process if flagged for a restart. So it maybe best to add the handler to the task making the change.

**Comment by sygilber** [comment]
https://github.com/IBM-Security/isam-ansible-roles/pull/61

Retested and working good.

Thank you Ram
