### ISSUE TITLE
Can I use variable replacement inside of pdadmin command files

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#6]
I have enough use cases where the variance is slight enough to need to externalize it, but to not want to maintain more vars

**pdadmin command file contents:

"server task {{ isam_server_instance }} list"**

ansible-playbook -i inventories/0-DFLT pdadmin.yml -v -e "da_name=jason_test execute_pdadmin_domain=Default9 isam_server_instance=jason_test-webseald-localhost" | sed 's/\\n/\n/g'

It does the substitution and visually appears accurate, but I get a server not found message.

Thanks

**Comment by ram-ibm** [comment]
Could you paste details of the error message please? It is not clear what the issue really is.

**Comment by Scoi4101** [comment]
ansible-playbook -i inventories/0-DFLT pdadmin.yml -v -l ciaisawd0005 -e "da_name=jason_test execute_pdadmin_domain=Default9 isam_server_instance=jason_test-webseald-ciaisawd0005" | sed 's/\\n/\n/g'

TASK [execute_pdadmin : Output of PDAdmin command execution] *******************
ok: [ciaisawd0005] => {
    "msg": [
        "cmd> server task jason_test-webseald-ciaisawd0005 list",
        "Could not perform the administration request",
        "Error: HPDMG0452E   Server not found. (status 0x14c011c4)",

**Comment by ram-ibm** [comment]
Could you run "server list" pdadmin command? I want to make sure that works and lists the server you have.

**Comment by Scoi4101** [comment]
**\"cmd&gt; server list\
    jason_test-webseald-ciaisawd0005.sys.cigna.com\
    ivmgrd-master\**
cmd&gt; &quot;server task jason_test-webseald-ciaisawd0005.sys.cigna.com list&quot;\
Error: Unknown command. Try using 'help' for a list of commands\"}",

**Comment by jldement** [comment]
Is this still an issue?  I have tried it multiple ways today and everything works correctly.  My input file (pdadmin_file) looks like this:
server list
server task default-webseald-isam9021dz list
Nothing fancy but the commands to get run against the domain specified (either in the yml file or on the command line as you show with the "-e" option.

**Comment by Scoi4101** [comment]
Its just being lazy.
An example is we have multiple environments that get setup the same (clones of the same instance)
So we would run commands like this where da_name is the instance name

acl attach /WebSEAL/{{ da_name }}/myjunction unauth
or the other command above
server task {{ isam_server_instance }} list

The ansible variable replacement works but something in the format of the commands to the REST call isn't happy

I have done this with YML files but the pdadmin file is just so easy

**Comment by jldement** [comment]
How are you feeding in your pdadmin commands?  A file or in the YML.  Something like this works fine:
 execute_pdadmin_commands: "server list\nserver task {{ instance }} list"
in my pdadmin.yml file.

**Comment by Scoi4101** [comment]
Its was the file based process i was trying.
The YML based solution works very well and handles all of the variable replacements with no issues.
