### ISSUE TITLE
Add node to cluster returns 500 code

### ISSUE THREAD

**Issue by wdwill2wdwill2** [IBM-Security/isam-ansible-roles#7]
Although I get a 500 error, it does add the node to the cluster.

Here is my playbook...
---
# Build out entire environment

- name: Setup Reverse Proxy Appliance
  hosts: reverseproxy
  connection: local
  roles:
    - role: add_cluster_node
      tags: ["cluster", "add"]
      add_cluster_node_signature_file: "./files/clustersign/primary.sign"
      add_cluster_node_restricted:     True

Here is the output from the screen.

fatal: [ciaisawd0016.sys.cigna.com]: FAILED! => {"changed": false, "failed": true, "log": "[2017-04-20 20:57:14,473] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.user.applianceuser] [__init__():9] Creating a user\n[2017-04-20 20:57:14,473] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.user.user] [__init__():8] Creating a user\n[2017-04-20 20:57:14,473] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.isamappliance] [__init__():11] Creating an ISAMAppliance\n[2017-04-20 20:57:14,473] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [__init__():15] Creating an IBMAppliance\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():28] *** Retrieving firmware ***\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():90] Checking for minimum version: None.\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():106] Checking for one of required modules: None.\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():123] Warnings: []\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():293] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():297] Input Data: {}\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():33] Suppressing SSL Warnings.\n[2017-04-20 20:57:14,475] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():22] Issuing request to: https://ciaisawd0016.sys.cigna.com:443/firmware_settings\n[2017-04-20 20:57:14,838] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():61] Status Code: 200\n[2017-04-20 20:57:14,838] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Text: [{\"partition\":\"1 (Active)\",\"last_boot\":\"1492704508\",\"name\":\"isam_9.0.2.0_20161102-2353\",\"active\":true,\"comment\":\"\",\"id\":1,\"firmware_version\":\"IBM Security Access Manager 9.0.2.0\",\"install_date\":\"1487600798\",\"backup_date\":null,\"install_type\":\"ISO\"}, {\"partition\":\"2\",\"last_boot\":\"Never\",\"name\":\"isam_9.0.2.0_20161102-2353\",\"active\":false,\"comment\":\"\",\"id\":2,\"firmware_version\":\"IBM Security Access Manager 9.0.2.0\",\"install_date\":\"1487600816\",\"backup_date\":null,\"install_type\":\"ISO\"}]\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():28] *** Get Setup Complete Settings ***\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():90] Checking for minimum version: None.\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():106] Checking for one of required modules: None.\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():123] Warnings: []\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():293] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():297] Input Data: {}\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():33] Suppressing SSL Warnings.\n[2017-04-20 20:57:14,839] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():22] Issuing request to: https://ciaisawd0016.sys.cigna.com:443/setup_complete\n[2017-04-20 20:57:14,882] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():61] Status Code: 200\n[2017-04-20 20:57:14,883] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Text: { \"configured\": true}\n[2017-04-20 20:57:14,883] [PID:2664 TID:139910666479424] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():28] *** Retrieving activations ***\n[2017-04-20 20:57:14,883] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():90] Checking for minimum version: None.\n[2017-04-20 20:57:14,883] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():106] Checking for one of required modules: None.\n[2017-04-20 20:57:14,884] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():123] Warnings: []\n[2017-04-20 20:57:14,884] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():293] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-04-20 20:57:14,884] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():297] Input Data: {}\n[2017-04-20 20:57:14,884] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():33] Suppressing SSL Warnings.\n[2017-04-20 20:57:14,884] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():22] Issuing request to: https://ciaisawd0016.sys.cigna.com:443/isam/capabilities/v1\n[2017-04-20 20:57:14,987] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():61] Status Code: 200\n[2017-04-20 20:57:14,987] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Text: [{\"name\":\"ISAM Base Appliance\",\"description\":\"IBM Security Access Manager Base Appliance\",\"id\":\"wga\",\"enabled\":\"True\"}]\n[2017-04-20 20:57:14,988] [PID:2664 TID:139910666479424] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():28] *** Retrieve the cluster identifier ***\n[2017-04-20 20:57:14,988] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():90] Checking for minimum version: None.\n[2017-04-20 20:57:14,988] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():106] Checking for one of required modules: None.\n[2017-04-20 20:57:14,989] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():123] Warnings: []\n[2017-04-20 20:57:14,989] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():293] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-04-20 20:57:14,989] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():297] Input Data: {}\n[2017-04-20 20:57:14,989] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():33] Suppressing SSL Warnings.\n[2017-04-20 20:57:14,989] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():22] Issuing request to: https://ciaisawd0016.sys.cigna.com:443/isam/cluster/id/v2\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():61] Status Code: 200\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Text: {\"value\":\"10.27.66.252\"}\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():28] *** List the current nodes in the cluster ***\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():90] Checking for minimum version: None.\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():106] Checking for one of required modules: None.\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():123] Warnings: []\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():293] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():297] Input Data: {}\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():33] Suppressing SSL Warnings.\n[2017-04-20 20:57:15,197] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():22] Issuing request to: https://ciaisawd0016.sys.cigna.com:443/isam/cluster/nodes/v1\n[2017-04-20 20:57:15,446] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():61] Status Code: 200\n[2017-04-20 20:57:15,446] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():63] Text: []\n[2017-04-20 20:57:15,446] [PID:2664 TID:139910666479424] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():28] *** Add a node to the cluster ***\n[2017-04-20 20:57:15,447] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():90] Checking for minimum version: None.\n[2017-04-20 20:57:15,447] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():106] Checking for one of required modules: None.\n[2017-04-20 20:57:15,447] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():123] Warnings: []\n[2017-04-20 20:57:15,447] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [invoke_post_files():144] Headers are: {'Accept': 'application/json,text/html,application/xhtml+xml,application/xml'}\n[2017-04-20 20:57:15,447] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():33] Suppressing SSL Warnings.\n[2017-04-20 20:57:15,447] [PID:2664 TID:139910666479424] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():22] Issuing request to: https://ciaisawd0016.sys.cigna.com:443/isam/cluster/nodes/v1\n[2017-04-20 20:57:21,822] [PID:2664 TID:139910666479424] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():44]   Request failed: \n[2017-04-20 20:57:21,823] [PID:2664 TID:139910666479424] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():45]      status code: 500\n[2017-04-20 20:57:21,823] [PID:2664 TID:139910666479424] [ERROR] [ibmsecurity.appliance.ibmappliance] [_process_response():47]      text: {\"message\":\"Error: DPWAP0003I   An error occured while executing the command: /usr/sbin/mesa_control commit /tmp/clusterp (0x4)\"}\n", "msg": "('HTTP Return code: 500', u'{\"message\":\"Error: DPWAP0003I   An error occured while executing the command: /usr/sbin/mesa_control commit /tmp/clusterp (0x4)\"}')", "name": "ibmsecurity.isam.base.cluster.node.add"}

**Comment by ram-ibm** [comment]
I will need to re-create this - the error seems to come from within the appliance. Will get back when I get to spend some time on this.

**Comment by jldement** [comment]
I have run this role a half dozen times and cannot recreate the issue.  Does it happen consistently across multiple nodes?

**Comment by ram-ibm** [comment]
Please upgrade to the latest "ibmsecurity" python package. I was able to re-create and fix the issue. Once you confirm that it is working for you - we can close this out.

**Comment by wdwill2wdwill2** [comment]
Thanks Ram.

I will get to this later this week and let you know.

Bill

**Comment by wdwill2wdwill2** [comment]
Ram the latest version fix my issue, thanks so much.
