### ISSUE TITLE
Management Authorization

### ISSUE THREAD

**Issue by wdwill2wdwill2** [IBM-Security/isam-ansible-roles#9]
Do the modules support enabling "Enabling Authorization Roles"?

I looked at the set_mgmtazn_role_features role but it looked like to just defined a role and did not enable the authorization roles.

Thanks
Bill

**Comment by ram-ibm** [comment]
There is a switch_auth role that handles externalizing appliance authentication to an external LDAP. You can always create separate roles for each of the steps it does.

**Comment by Ardun21** [comment]
Is there functionality to create a custom authorization role?  I'm not seeing it and it looks like switch_auth only works on the built-in roles.

**Comment by ram-ibm** [comment]
The Python code to create custom authorization roles exist. You may want to create your own role to leverage it. Let me know if you have issues creating such a role.

**Comment by Ardun21** [comment]
I have been able to successfully create a role that I've named add_mgmtazn_role.  I'd be happy to open a PR and contribute it back.  I also will be looking into creating roles for some other functions related to management authorization groups (i.e. adding users/groups, manipulating features, etc.)

**Comment by ram-ibm** [comment]
Really appreciate that. Please submit a pull request. Thank you.

**Comment by Ardun21** [comment]
Opened Pull Request #12

**Comment by ram-ibm** [comment]
Merged pull request.
